
FROM python:3.9 as build

# Create a virtualenv for dependencies. This isolates these packages from
# system-level packages.
# Use -p python3 or -p python3.7 to select python version. Default is version 2.
RUN virtualenv /env -p python3

# Setting these environment variables are the same as running
# source /env/bin/activate.
ENV VIRTUAL_ENV /env
ENV PATH /env/bin:$PATH

FROM build
COPY requirements.render.txt /app/requirements.render.txt
RUN pip install -r /app/requirements.render.txt
