GOOGLE_CLOUD_PROJECT: "py-rest-service-template-local"
GOOGLE_CLOUD_LOCATION: "asia-northeast1"
RUNTIME: "python38"
PORT: "8081"
INSTANCE_CLASS: "F1"

QUEUE_RATE_STORER: "10/s"
QUEUE_MAX_CONCURRENT_REQUESTS_STORER: "10"

QUEUE_RATE_DERIVER: "10/s"
QUEUE_MAX_CONCURRENT_REQUESTS_DERIVER: "10"

ENV_VARIABLES: |
 env_variables:
  PUBSUB_EMULATOR_HOST: localhost:8171
  DATASTORE_EMULATOR_HOST: localhost:8814
