GOOGLE_CLOUD_LOCATION: "us-central1"
RUNTIME: "python38"
PORT: "8081"

INSTANCE_CLASS: "F2"
LOGIN_ADMIN: "login: admin"

QUEUE_RATE_STORER: "100/s"
QUEUE_MAX_CONCURRENT_REQUESTS_STORER: "10"

QUEUE_RATE_DERIVER: "100/s"
QUEUE_MAX_CONCURRENT_REQUESTS_DERIVER: "20"

