GOOGLE_CLOUD_LOCATION: "australia-southeast1"
RUNTIME: "python38"
PORT: "8081"

INSTANCE_CLASS: "F1"

QUEUE_RATE_STORER: "50/s"
QUEUE_MAX_CONCURRENT_REQUESTS_STORER: "10"

QUEUE_RATE_DERIVER: "50/s"
QUEUE_MAX_CONCURRENT_REQUESTS_DERIVER: "10"

