GOOGLE_CLOUD_LOCATION: "asia-northeast1"
RUNTIME: "python38"
PORT: "8081"

INSTANCE_CLASS: "F2"

QUEUE_RATE_STORER: "100/s"
QUEUE_MAX_CONCURRENT_REQUESTS_STORER: "10"

QUEUE_RATE_DERIVER: "100/s"
QUEUE_MAX_CONCURRENT_REQUESTS_DERIVER: "20"
